#! /bin/bash

if [ ! -d ~/.trash ]
then 
	mkdir ~/.trash
fi

if test $# -eq 0
then
	echo "Usuage : delete file1 [file2 file3 ....]"
else
	echo "You are going to delete these files"
	echo $@

	echo "Are you going to delete these files?Yes/No"
	read reply
	if [ $reply != 'n' ] && [ $reply != 'N' ] && [ $reply != "No" ] && [ $reply != "no" ]
	then 
		for file in $@
		do	
			if [ -d $file -o -f $file ]
			then
				mv -b $file ~/.trash
				echo "$file has been deleted."
			else
				echo "No such file or directory."
			fi
		done
	else
		echo "No file(s) to move."
	fi
fi

echo "Finished."
