#! /bin/bash

echo "Please input an integer n(>0)"

while read n
do
	sum=0
	number=1

	if [ $n -gt 0 ]
	then
		while test $number -le $n
		do
			let sum=$sum+$number
			number=$[$number+1]
		done

		echo "The sum of 1+2+...+$n is $sum"
	else
		echo "Please input a integer bigger than zero"
	fi

	echo "Please input an integer n(>0)"
	
done
